version: '3.9'
services:
  blockchain:
    build:
      context: .
      dockerfile: Dockerfile
      target: blockchain
    ports:
      - 8545:8545
    secrets:
      - test_acc1_priv_key
      - test_acc2_priv_key
    volumes:
      - ganachedb:/opt/db

secrets:
  test_acc1_priv_key:
    file: '../../eva-investments-resources/accounts/.secrets/test_acc1_priv_key'
  test_acc2_priv_key:
    file: '../../eva-investments-resources/accounts/.secrets/test_acc2_priv_key'

volumes:
  ganachedb: