export const BLOCKCHAIN_COMMUNICATION_NODES_OPTIONS_ENV_KEY =
  'BLOCKCHAIN_COMMUNICATION_NODES_OPTIONS';
export const BLOCKCHAIN_COMMUNICATION_NODES_AUTH_ENV_KEY =
  'BLOCKCHAIN_COMMUNICATION_NODES_AUTH';
